databases:
  - name: learn-coach-db
    databaseName: learn_coach
    user: learn_coach
    plan: free

services:
  - type: web
    name: learn-coach-service
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn lc_service.api.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: lc_service.settings.django
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_ALLOWED_HOSTS
        value: ""
      - key: CORS_ALLOWED_ORIGINS
        value: "https://learn-coach-ui.vercel.app"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://learn-coach-ui.vercel.app"
      - key: DATABASE_URL
        fromDatabase:
          name: learn-coach-db
          property: connectionString
