# Generated by Django 6.1.1 on 2026-09-24 00:06

import django.core.validators
import django.db.models.deletion
import lc_service.api.resources.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('book', 'Book'), ('paper', 'Paper')], max_length=16)),
                ('subject', models.CharField(choices=[('biology', 'Biology'), ('mathematics', 'Mathematics'), ('statistics', 'Statistics'), ('electronics', 'Electronics')], max_length=32)),
                ('file', models.FileField(upload_to=lc_service.api.resources.models.resource_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('title_status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
